### ISSUE TITLE
Updating intl_en_US.arb fails with new version of gen_l10n.dart script

### ISSUE THREAD

**Issue by perclasson** [material-components/material-components-flutter-gallery#532]
After https://github.com/flutter/flutter/pull/49357 it seems as if the gen_l10n.dart has changed a bit (reverting it makes the script run as before `git revert -m1 7539826d7b6bb8d5f2417d8d58bbc4ebe6d3ed42`).

The script now complains, as some of our placeholders have incorrectly formatted example values. For example:
```
  fatal: The value of the "destinationName" placeholder attribute for message "cardsDemoExploreSemantics", is not properly formatted. Ensure that it is a map with string valued keys.
```

Even after that is fixed, the script now fails with the following error message:

```dart
  Unhandled exception:
  Error in <unknown source>: Expected to find ';'.

  Error in <unknown source>: Expected an identifier.

  Error in <unknown source>: Expected an identifier.

  #0      _parseSource (package:analyzer/analyzer.dart:155:52)
  #1      parseCompilationUnit (package:analyzer/analyzer.dart:58:10)
  #2      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:100:16)
  #3      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:87:14)
  #4      main.<anonymous closure> (file:///Users/perc/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.9/bin/generate_from_arb.dart:113:33)
  #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
  #6      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
  #7      main (file:///Users/perc/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.9/bin/generate_from_arb.dart:116:23)
  #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  pub finished with exit code 255

failed with exit code 1
```

Figure out the root cause and fix/file a flutter/flutter issue.

**Comment by perclasson** [comment]
I created https://github.com/flutter/flutter/issues/49689 for this right now as I couldn't find any root cause except that the above commit seems to have caused the issue. Moving this to blocked for now.
